datatype: Infinigen
type: "coco"
year: 2023

folder: test # name of source folder
test_split: 0.2 # set to blank for default (used in urchin)

ooi:
  - "handfish"
#  - "urchin"
#  - "fish"
#  - "crustacean"
#  - "coral"
#  - "boulder"
#  - "rock" # yes
#  - "plasticbag"
#  - "cube" # sometimes colourboard or cube
#  - "Kina"

coco_mapping:
  - "Handfish"
#  - "Urchin"
#  - "Fish"
#  - "Crustacean"
#  - "Coral"
#  - "Boulder"
#  - "Rock"
#  - "Plastic"
#  - "Board"
#  - "plastic"
#  - "colourboard"
#  - "spinylobster"
#  - "kina"

