#defaults:
folder: test # include water or no water in name when running generate_coco_annotations
type: "coco"
num_classes: 2 # includes background
year: 2023

datatype: Infinigen
test_split: 0.2 # set to blank for default (used in urchin)

ooi:
  - "handfish"
#  - "urchin"
#  - "fish"
#  - "crustacean"
#  - "coral"
#  - "boulder"
#  - "rock" # yes
#  - "plasticbag"
#  - "cube" # sometimes colourboard or cube
#  - "Kina"

coco_mapping:
  - "Handfish"
#  - "Urchin"
#  - "Fish"
#  - "Crustacean"
#  - "Coral"
#  - "Boulder"
#  - "Rock"
#  - "Plastic"
#  - "Board"
#  - "plastic"
#  - "colourboard"
#  - "spinylobster"
#  - "kina"

