defaults:
  - squidle_default
folder: squidle_handfish_default

coco_mapping:
  - "Handfish"
#  - "Helicolenus"
#  - "Caesio"

# Generating squidle / coco datsets
test_split: 0.30 # set to blank for default (used in urchin)
ratio_non_annotated_images: 1
inclusive: True
annotation_set_ids:
needs_review_annotation_set_ids:
exclude_annotation_set_ids:
squidle_mapping:
  - 13450 # handfish
#  - 7312 # helico
#  - 7311 # caesio
#  - 1821
#  - 1822
  #- 534 # sea urchin
