defaults:
  - squidle_default

folder: squidle_east_tas_urchins
test_split: 0.0 # 

ratio_non_annotated_images: 1
inclusive: True
annotation_set_ids:
  - 13088 # East Tasmania, ClimateChangeAI
  # - 10690 #urchin 2009
  #- 12479 # urchin 2011

coco_mapping:
  - "Seaurchin"
squidle_mapping:
  - 13029 # sea urchin
  - 

needs_review_annotation_set_ids:
exclude_annotation_sets:

