type: "coco"
year: 2023
datatype: Squidle
exclude_annotation_set_ids:
needs_review_annotation_set_ids:
  -
api_token: "71d4d92dcea8391bec807c36ee8c77e7443e1a44f703d274168b9347" # select user api token
annotate_api_token: "71d4d92dcea8391bec807c36ee8c77e7443e1a44f703d274168b9347" # annotator(write) user api token
url: "https://squidle.org/"