defaults:
  - squidle_default

folder: squidle_redcup_train
test_split: 0.0 # 

ratio_non_annotated_images: 1
inclusive: True
annotation_set_ids: 
  - 
coco_mapping:
  - " Gorgonian Red"
  #- "Red Cup Smooth"
  #- "Red Cup Smooth - Bleached"
squidle_mapping:
  - 7158 # gorgonian red pteronisis like
  #- 7111 # red cup smooth
  #- 13288 # red cup bleached NOT USED

needs_review_annotation_set_ids:
  - 13249
exclude_annotation_set_ids:
  - 13250
  - 13251


