defaults:
  - squidle_hand_default
folder: sq_hand_train85_valv2
test_split: 1.0 # set to blank for default (used in urchin)
inclusive: True
annotation_set_ids:
  - 13496 # 6 handfish
exclude_annotation_set_ids:
