defaults:
  - squidle_hand_default
folder: sq_hand_train85_n200_ext
test_split: 0.0 # set to blank for default (used in urchin)
inclusive: True
ratio_non_annotated_images: 0
annotation_set_ids:
  - 13497
  - 13498
  - 13499
  - 13500
  - 14174 # adjacent images of train85
  - 14188 # adjacent images of test15
exclude_annotation_set_ids:
  - 13496 # val
  - 13372 # test

